language: generic
sudo: required
services:
  - docker

before_install: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install: sudo docker run --rm --privileged multiarch/qemu-user-static:register
script:
  - bash -x ./build.sh
