language: generic
sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

jobs:
  include:
    - stage: update
      script: ./update.sh

    - stage: build
      env: ARCH=amd64
      script: ./build.sh -v ${ARCH}

    - stage: build
      env: ARCH=arm32v6
      script: ./build.sh -v ${ARCH}

    - stage: build
      env: ARCH=arm64v8
      script: ./build.sh -v ${ARCH}

    - stage: push
      script: ./build.sh manifest

stages:
  - name: update
    if: branch = master
  - name: build
    if: tag =~ /v\d+\.\d+\.\d+/
  - name: push
    if: tag =~ /v\d+\.\d+\.\d+/

before_install: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install: bash -x ./travis-install.sh
