language: generic
sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install: bash -x ./travis-install.sh
script: bash -x ./build.sh
