version: "3.7"
services:
  mongodb:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - db:/data/db
    networks:
      - unifi

  unifi:
    build:
      context: .
      args:
        - UNIFI_CONTROLLER_VERSION=${UNIFI_CONTROLLER_VERSION:-latest}
    init: true
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
    environment:
      PUID: "1000"
      PGID: "1000"
      MEM_LIMIT: 1024M
      MEM_STARTUP: 1024M
      DB_URI: mongodb://mongodb/unifi
      STATDB_URI: mongodb://mongodb/unifi_stat
      DB_NAME: unifi
      RUNAS_UID0: "true"
    ports:
      - "3478:3478/udp" # Port used for STUN
      - "8080:8080/tcp" # Port used for device and controller communication
      - "8443:8443/tcp" # Port used for controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # Port used for HTTP portal redirection
      - "8843:8843/tcp" # Port used for HTTPS portal redirection
      - "6789:6789/tcp" # Port used for UniFi mobile speed test
      - "10001:10001/udp" # Port used for AP discovery
      - "1900:1900/udp" # Port used for "Make controller discoverable on L2 network" in controller settings
    networks:
      - unifi

volumes:
  db: {}
  data: {}
  log: {}
  cert: {}
  init: {}

networks:
  unifi: {}
