name: Check for updates
on:
  schedule:
    - cron: "0 1 * * 1,4"

jobs:
  check:
    name: Check for updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_DEPLOY_TOKEN }}

      - name: Install node
        uses: actions/setup-node@v2.1.3
        with:
          node-version: "13.x"

      - name: Install node modules
        run: npm ci

      - name: Check for updates
        run: env GITHUB_TOKEN="${{ secrets.GH_DEPLOY_TOKEN }}" ./update.sh
