name: Continous Integration
on:
  push:
    branches: ["*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.0
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Buildx
        run: |
          docker buildx bake \
            --set "controller.args.VER=$(<VERSION)" \
            --set "controller.tags=docker.io/alxandr/unifi-controller:latest" \
            --set "controller.tags=docker.io/alxandr/unifi-controller:v$(<VERSION)"
