name: Publish
on:
  workflow_dispatch: {}
  push:
    branches: ["*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Read .env
        uses: c-py/action-dotenv-to-setenv@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          version: latest

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Buildx
        run: |
          docker buildx bake \
            --set "controller.tags=ghcr.io/alxandr/unifi-controller:latest" \
            --set "controller.tags=ghcr.io/alxandr/unifi-controller:v${UNIFI_CONTROLLER_VERSION}" \
            --set "controller.output=type=registry"
