name: Publish
on:
  workflow_dispatch: {}
  push:
    tags: ["v*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          version: latest

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Buildx
        run: |
          docker buildx bake \
            --set "controller.args.VER=$(<VERSION)" \
            --set "controller.tags=docker.io/alxandr/unifi-controller:latest" \
            --set "controller.tags=docker.io/alxandr/unifi-controller:v$(<VERSION)" \
            --set "controller.output=type=registry"
